"""Add discord avatar

Revision ID: 02c66a5d6635
Revises: 6bbeaf4ecda2
Create Date: 2022-08-22 02:09:00.794012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c66a5d6635'
down_revision = '6bbeaf4ecda2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_accounts', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discord_accounts', 'avatar')
    # ### end Alembic commands ###
